/* 
 * TezosAPI
 *
 * BETA Tezos API, this may change frequently
 *
 * OpenAPI spec version: 0.0.2
 * Contact: office@bitfly.at
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tezex

import (
	"time"
)

// Account Information
type Account struct {

	Address string `json:"address,omitempty"`

	OperationCount int32 `json:"operation_count,omitempty"`

	SentTransactionCount int32 `json:"sent_transaction_count,omitempty"`

	RecvTransactionCount int32 `json:"recv_transaction_count,omitempty"`

	OriginationCount int32 `json:"origination_count,omitempty"`

	DelegationCount int32 `json:"delegation_count,omitempty"`

	DelegatedCount int32 `json:"delegated_count,omitempty"`

	EndorsementCount int32 `json:"endorsement_count,omitempty"`

	FirstSeen time.Time `json:"first_seen,omitempty"`

	LastSeen time.Time `json:"last_seen,omitempty"`

	Name string `json:"name,omitempty"`

	Balance string `json:"balance,omitempty"`

	TotalSent string `json:"total_sent,omitempty"`

	TotalReceived string `json:"total_received,omitempty"`

	BakedBlocks int32 `json:"baked_blocks,omitempty"`

	ImageUrl string `json:"image_url,omitempty"`
}
