/* 
 * TezosAPI
 *
 * BETA Tezos API, this may change frequently
 *
 * OpenAPI spec version: 0.0.2
 * Contact: office@bitfly.at
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tezex

import (
	"time"
)

type Block struct {

	Hash string `json:"hash,omitempty"`

	NetId string `json:"net_id,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Level int32 `json:"level,omitempty"`

	Proto string `json:"proto,omitempty"`

	Successors []ChainStatus `json:"successors,omitempty"`

	Predecessor string `json:"predecessor,omitempty"`

	Time time.Time `json:"time,omitempty"`

	ValidationPass string `json:"validation_pass,omitempty"`

	Data string `json:"data,omitempty"`

	ChainStatus string `json:"chain_status,omitempty"`

	OperationsCount int32 `json:"operations_count,omitempty"`

	OperationsHash string `json:"operations_hash,omitempty"`

	Baker string `json:"baker,omitempty"`

	SeedNonceHash string `json:"seed_nonce_hash,omitempty"`

	ProofOfWorkNonce string `json:"proof_of_work_nonce,omitempty"`

	Signature string `json:"signature,omitempty"`

	Priority int32 `json:"priority,omitempty"`

	OperationCount int32 `json:"operation_count,omitempty"`

	TotalFee string `json:"total_fee,omitempty"`

	Operations BlockOperationsSorted `json:"operations,omitempty"`
}
