/* 
 * TezosAPI
 *
 * BETA Tezos API, this may change frequently
 *
 * OpenAPI spec version: 0.0.2
 * Contact: office@bitfly.at
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tezex

type OriginationOperation struct {

	Kind string `json:"kind,omitempty"`

	ManagerPubkey string `json:"manager_pubkey,omitempty"`

	Balance int32 `json:"balance,omitempty"`

	Spendable bool `json:"spendable,omitempty"`

	Delegateable bool `json:"delegateable,omitempty"`

	Delegate string `json:"delegate,omitempty"`

	Script TezosScript `json:"script,omitempty"`

	Storage TezosScript `json:"storage,omitempty"`
}
